### ISSUE TITLE
computed和watch有冲突

### ISSUE THREAD

**Issue by githublyp** [ecomfe/okam#11]
单独使用watch就可以，两个一起使用就有问题

**Comment by wuhy** [comment]
@githublyp 可以具体描述下问题是什么吗？然后你可以跟另外你提的问题，一并再看下，不知道那个问题跟你这个问题是否有一定关联性

**Comment by githublyp** [comment]
watch调用两次
watch: {
      userInfo: {
        handler() {
          // 当用户登录完后请求业务逻辑
          this.userInfo.uid && this.getUserInfo()
        },
        deep: true
      }
    },

**Comment by wuhy** [comment]
@githublyp 没太懂，你这里描述跟标题描述 computed 和 watch 使用冲突有什么直接关系吗？可以具体点描述下你的现象和问题吗？还有 watch 调用两次，具体是做了什么事情触发了两次了？

**Comment by wuhy** [comment]
@githublyp userInfo 什么时候设置的，具体怎么设置修改的？是你在外部发起异步请求，更新 store userInfo，然后 watch 这里 handler 触发了两次？然后还有个问题，为啥watch handler 里要手动触发生命周期钩子，这个钩子方法是不应该开发者自己去触发调用的

**Comment by githublyp** [comment]
userInfo 在外部发起异步请求，更新 store userInfo，然后 watch 这里 handler 触发了两次；

**Comment by wuhy** [comment]
> userInfo 在外部发起异步请求，更新 store userInfo，然后 watch 这里 handler 触发了两次；

我这边看下能不能复现你的问题

**Comment by githublyp** [comment]
这是reducer:
![image](https://user-images.githubusercontent.com/12792918/49267960-d2486900-f497-11e8-8445-3afc08e44518.png)
异步更新了：
SET_STATE_STATUS
SET_STATE_USERINFO

不知道是不是redux的问题

**Comment by wuhy** [comment]
> 这是reducer:
> ![image](https://user-images.githubusercontent.com/12792918/49267960-d2486900-f497-11e8-8445-3afc08e44518.png)
> 异步更新了：
> SET_STATE_STATUS
> SET_STATE_USERINFO
> 
> 不知道是不是redux的问题

大概知道什么问题了，目前实现机制是只要 store 有变化会把所有依赖的 computed props 都重新触发一次计算，导致你这边触发了两次，我这边看下做下优化吧。

**Comment by wuhy** [comment]
@githublyp 你可以更新到最新 0.4.0-beta.3 看下这里问题，这里做了下优化，具体修改逻辑可以看关联的 commit 记录，我先把这个 issue 关了，有问题再 open~
