### ISSUE TITLE
升级之后运行不了项目了

### ISSUE THREAD

**Issue by githublyp** [ecomfe/okam#16]
## 问题类型

* [ ] 如何实现某功能
* [x ] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情

okam upgrade project
之后运行不了项目

### 实际情况

![image](https://user-images.githubusercontent.com/12792918/49322080-e008f780-f546-11e8-964b-74db48fd41bd.png)

### 问题环境

okam 相关包版本
    `okam-core` 版本:0.4.0-beta.0
    `okam-build` 版本:0.4.0-beta.0
    `okam-cli` 版本(若是 cli 问题):0.1.0-beta.0

运行环境
    微信小程序开发工具 or 真机

**Comment by The-only** [comment]
@githublyp 辛苦看一下
1. 项目是从原先okam为0.3版本的项目中执行`okam upgrade project`升级的吗？(理论上这种情况下upgrade project 包版本是不会从0.3升为0.4只会升.3的小版本，你看看本地okam-build okam-core 的具体版本是多少?`okam --version && npm ls okam-build okam-core`)；
2. build过程中 或者 运行过程中有没有什么报错？
  若是 0.3 升级到了 0.4 有两个 breakchange: 看看是否有用到下面两个 breakchange，改完能否解决问题？
     - okam-core: break change 移除 App/页面/自定义组件实例上下文的 $global 属性, [具体解决方案](https://ecomfe.github.io/okam/#/app/entry?id=app-%E6%89%A9%E5%B1%95-api)
     -  okam-build: break change 变更构建配置 component.template.transformTags 模板标签转换配置定义，新增构建 API reverseTagMap 进行兼容转换，[具体解决方案](https://ecomfe.github.io/okam/#/build/transformTag)
3. 若用cli构建的项目，你选择的模板、脚本、样式语法分别是？是否有用到 tag 标签转换？
若上面不能解决，描述一下复现场景，方便的话可以给个问题的代码示例，我具体看看

**Comment by githublyp** [comment]
直接用okam init test之后，运行npm run dev:wx 打包之后生成wx_dist但是app.js 等放在src目录下；还有在app.less中@import其他样式的时候打包不报错，但是不会引入okam框架；也就是wx_dist/common/下没有okam等框架文件：
![image](https://user-images.githubusercontent.com/12792918/49323970-7b0dcb80-f55f-11e8-963a-9aac87a64d7f.png)

**Comment by githublyp** [comment]
![image](https://user-images.githubusercontent.com/12792918/49324652-21140280-f56d-11e8-8df6-ec82f647b952.png)

![image](https://user-images.githubusercontent.com/12792918/49324711-6edd3a80-f56e-11e8-811c-ed9f3a50fd04.png)

**Comment by wuhy** [comment]
@githublyp 更新到 0.4.0-beta.1 再看下，我先把 issue 关闭，如有问题再打开，thks~
