### ISSUE TITLE
[ERROR] src/common/img/loading.gif skipped

### ISSUE THREAD

**Issue by 422656004** [ecomfe/okam#19]
图片14k 不支持 gif 图片吗？

## 问题类型

* [ ] 如何实现某功能
* [ ] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

**Comment by wuhy** [comment]
不应该被跳过，目前没有做图片的依赖分析，源码下的图片理论上都会输出，我这边看下

**Comment by wuhy** [comment]
@422656004 这个问题主要是图片压缩处理器对于 gif 不支持失败，导致图片没有输出，明天会发布个版本优化下

**Comment by The-only** [comment]
@422656004 不好意思，问题已修复发版， 辛苦将 `okam-plugin-tinyimg`升级到最新版本: `npm install okam-plugin-tinyimg@latest`，感谢反馈
