### ISSUE TITLE
App 脚本 app.js 配置时 文档里面 这样配置编译不通过，把globalData放到config 里面就不报错

### ISSUE THREAD

**Issue by 422656004** [ecomfe/okam#20]
config: {
      pages: [
          'pages/home/index'
      ]
  },

  globalData: {}, // 全局应用数据定义，同原生小程序

## 问题类型

* [ ] 如何实现某功能
* [ ] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

**Comment by wuhy** [comment]
可以截图看下编译命令行输出的错误信息吗包括你编辑器实际代码截图？感觉是不是你的代码的语法有问题

**Comment by 422656004** [comment]
不好意思
问题时 globalData 在字段，不能包含有config 这个属性 
globalData: {
    interface: {
  }
}
编译不报错（百度智能小程序）

**Comment by wuhy** [comment]
@422656004 问题已修复，可以升级到 okam-build@0.4.3 再看看
