### ISSUE TITLE
template 中简写编译有误

### ISSUE THREAD

**Issue by baranwang** [ecomfe/okam#35]
* [ ] 如何实现某功能
* [x] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情

`:class` 采用简写编译有误

### 期望效果

```
:class="{ isx, blur }"
```
应编译为
```
class="{{[isx?'isx':'',blur?'blur':'']}}"
```

### 实际情况

```
class="{{[undefined?'isx':'',undefined?'blur':'']}}"
```

**Comment by wuhy** [comment]
@baranwang 你升级到 okam-build@0.4.19 再看看
