### ISSUE TITLE
内联样式当有逗号时编译错误

### ISSUE THREAD

**Issue by baranwang** [ecomfe/okam#37]
## 问题类型

* [x] 报 BUG
* [ ] 如何实现某功能
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情

```
:style="{ transform: 'translate(-50%, -50%) rotate(' + preview.rotate + 'deg)' }"
```

### 期望效果

```
style="transform: {{ 'translate(-50%, -50%) rotate(' + preview.rotate + 'deg)' }}"
```

### 实际情况

```
style="transform:{{'translate(-50%}};-50%) rotate(' + preview.rotate + 'deg)':{{-50%) rotate(' + preview.rotate + 'deg)'}}"
```

### 问题环境
`okam-build` 版本:0.4.19

---

另外补充一个问题内联样式使用 es6 写法也编译失败
eg: ``:style="{ width: `${width}px` }"`` 无法正常编译为 `style="width:{{ width }}px"`

**Comment by wuhy** [comment]
@baranwang transform 问题已修复， es6 模板字符串支持也做了支持，可以升级到 `okam-build@0.4.20` 再看下。由于目前实现机制是基于字符串简单分析做的转换，所以支持的写法是有限的，如再有任何问题欢迎反馈，谢谢~
