### ISSUE TITLE
why would it called Okam?

### ISSUE THREAD

**Issue by zzz6519003** [ecomfe/okam#42]

**Comment by wuhy** [comment]
The `okam` name comes from the `Occam's razor` principle (We name it`奥卡姆剃刀` in Chinese) and the pronunciation is like the Chinese `奥卡姆`. The framework name is not fully the same with the rule name, but we hope this framework is simpler enough to solve mini program problems and do not add unnecessary complexity.

**Comment by zzz6519003** [comment]
recommend  http://complexityexplorer.org
