### ISSUE TITLE
vuex下通过mutation或action更新数据后，视图不更新

### ISSUE THREAD

**Issue by yuanjianhang** [ecomfe/okam#43]
* [ ] 如何实现某功能
* [x ] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情
启用vuex管理状态，其中，store启用了modules功能。通过mutation更改state的值后，界面没有发生变化，console打印state相关值已经是更新过后的了。通过手动调用this.$fireStoreChange()才能触发视图的更新。
okam是用的最新版。

**Comment by aFcFzF** [comment]
哈哈怎么关啦？我也发现必须手动触发。
