### ISSUE TITLE
okam框架中如何使用百度小程序的动态库？

### ISSUE THREAD

**Issue by isliuwei** [ecomfe/okam#47]
## 问题类型

* [x] 如何实现某功能
* [ ] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情
okam框架中如何使用百度小程序的动态库？
https://smartprogram.baidu.com/docs/develop/framework/dynamiclib_use/

使用 “dynamicLib://myDynamicLib/special-list” 这种路径的形式 无法正确引入动态库文件

### 期望效果
说明如何使用百度小程序的动态库文件

**Comment by The-only** [comment]
在 `swan.config.js` 配置项中 添加 [resolve](https://ecomfe.github.io/okam/#/build/index?id=resolve) 配置项 

```
{
   // ...
    resolve: {
        ignore: /^(dynamicLib:\/\/)./
    },
   // ...
}
```
