### ISSUE TITLE
百度小程序无法找到 regeneratorRuntime 问题

### ISSUE THREAD

**Issue by qianliu013** [ecomfe/okam#53]
## 问题类型

* [ ] 如何实现某功能
* [x] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情

百度小程序近期上线了[非兼容性改动](https://smartprogram.baidu.com/forum/topic/show/74605)，这将导致无法在小程序中获取全局变量（如通过 window/root/global/`Function('return this')()` 等），
使得无法将一些属性挂载在全局变量，从而导致小程序运行异常。

典型的例子：使用了 async，编译后的代码运行会往全局变量挂载 regeneratorRuntime 属性。

对于 Okam 的影响：如果使用了 `polyfill: ['async']`（目前的 swan.config.js 默认配置），
请在 swan.config.js 中将 polyfill 改为 localPolyfill，并重新编译上传包

### 复现步骤 和  问题示例

代码中包含了 async，并且使用了 `polyfill: ['async']`

### 问题环境

- `okam-cli` 0.1.11
- 百度小程序环境：可参考公告内容

**Comment by xhong8023** [comment]
存量解决：在 swan.config.js 中将 polyfill 改为 localPolyfill，并重新编译上传包
![image](https://user-images.githubusercontent.com/3883322/81547321-4934a180-93ae-11ea-98ac-f4883c0557e3.png)

新增：我这边更新一下文档和最新cli，有进展，将更新状态

**Comment by xhong8023** [comment]
okam-cli  0.1.12 已发版，更新置最新, 百度小程序默认使用改为： `localPolyfil`
