### ISSUE TITLE
百度小程序Page.onInit中不支持通过赋值this.xxx修改视图

### ISSUE THREAD

**Issue by iqshen** [ecomfe/okam#54]
## 问题类型

* [ ] 如何实现某功能
* [x] 报 BUG
* [ ] 某功能改进建议
* [ ] 新功能建议
* [ ] 文档问题
* [ ] 其他/以上都不是

## 问题详情
百度小程序提供的新的页面级生命周期 Page.onInit ，执行时机介于 App.onLaunch 、Page.onLoad之间， 使用okam不支持在Page.onInit函数中通过this.xx赋值的方式修改视图。

### 期望效果
在Page.onInit中通过赋值this.xx可以修改视图

### 实际情况
在onInit中给this.xxx赋值不能修改视图

### 复现步骤 和  问题示例
略

### 问题环境
    `okam-core` 版本:0.4.11
    `okam-build` 版本:0.4.17

**Comment by liujiaor** [comment]
该问题已解决，请升级到以下版本：
 - okam-build@0.4.27-alpha.0
 - okam-core@0.4.18-alpha.0
