### ISSUE TITLE
引用钉钉扩展组件，绑定的事件的参数并不是event.currentTarget.dataset导致报错

### ISSUE THREAD

**Issue by yinLiangDream** [ecomfe/okam#7]
```html
<template>
  <list-item @Click="clickItem" />
  <!-- 这种写法也无效 -->
  <!--<list-item @Click="clickItem(index)"> -->
</template>
<script>
export default {
  methods: {
    clickItem(){}
  }
}
</script>
```

![image.png](https://images.zenhubusercontent.com/5bea68470cefa317ea423fe8/af6a299d-b986-42c1-b837-d2e66e887464)

编译过后使用事件代理：

![image.png](https://images.zenhubusercontent.com/5bea68470cefa317ea423fe8/dd5e2997-fd09-4227-8764-e2d82a128887)

**Comment by wuhy** [comment]
嗯，支付宝原生组件需要适配下，感谢反馈

**Comment by wuhy** [comment]
@yinLiangDream 已修复，可以使用 0.3.1 版本再看看，这个 issue 我先关了
